### ISSUE TITLE
Jun 1 - ERC721 - практика

### ISSUE THREAD

**Issue by rlkvrv** [fullstack-development/blockchain-developers-roadmap#18]
https://github.com/fullstack-development/blockchain-developers-roadmap/blob/80fe8c4584d601df785f59d83698bf52bfdca858/solidity/junior-1/solidity/practice/4-nft-erc-721.md?plain=1#L10
Тут нужно выделить конкретные методы, например `transferFrom` и чем он отличается от `safeTransferFrom` в ERC721, так же чем отличаются `approve` и `setApproveForAll` (и как отозвать каждый из этих апрувов), `tokenURI` (какие особенности) и т.д.   

---

https://github.com/fullstack-development/blockchain-developers-roadmap/blob/80fe8c4584d601df785f59d83698bf52bfdca858/solidity/junior-1/solidity/practice/4-nft-erc-721.md?plain=1#L15-L16
А это все еще работает? В плане я недавно пробовал поработать в тестовом режиме и с пинатой и с nft.storage, кажется там есть изменения. В любом случае возможно стоит убрать привязку к конкретным сервисам.

---

https://github.com/fullstack-development/blockchain-developers-roadmap/blob/80fe8c4584d601df785f59d83698bf52bfdca858/solidity/junior-1/solidity/practice/4-nft-erc-721.md?plain=1#L17
Запустить для чего, может добавим уточнение? Я не совсем понимаю зачем ее запускать и что с этим делать)

---

https://github.com/fullstack-development/blockchain-developers-roadmap/blob/80fe8c4584d601df785f59d83698bf52bfdca858/solidity/junior-1/solidity/practice/4-nft-erc-721.md?plain=1#L37
Вопрос про хуки уже есть в задании по ERC20, я думаю его можно убрать.

---
https://github.com/fullstack-development/blockchain-developers-roadmap/blob/80fe8c4584d601df785f59d83698bf52bfdca858/solidity/junior-1/solidity/practice/4-nft-erc-721.md?plain=1#L46

Предлагаю - "Какое расширение нужно использовать?"

**Comment by PavelNaydanov** [comment]
Файл 4-nft-erc-721.md переехал в 3-erc-721.md. Правки делать в нем.
